---
name: tailwindcss-language-server
description: Language Server Protocol implementation for Tailwind CSS.
homepage: https://github.com/tailwindlabs/tailwindcss-intellisense
licenses:
  - MIT
languages:
  - CSS
categories:
  - LSP

source:
  id: pkg:npm/@tailwindcss/language-server@0.14.1

schemas:
  lsp: vscode:https://raw.githubusercontent.com/tailwindlabs/tailwindcss-intellisense/refs/tags/v0.14.1/packages/vscode-tailwindcss/package.json

bin:
  tailwindcss-language-server: npm:tailwindcss-language-server
